services:
  db:
    build: ./database
    container_name: grid_db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U $DB_USER -d $DB_NAME"]
      interval: 2s
      timeout: 20s
      retries: 7

  api:
    build: ./api
    container_name: grid_api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data:
